CREATE DATABASE IF NOT EXISTS db_testewk;
USE db_testewk;

DROP TABLE IF EXISTS `DB_TESTEWK`.`TB_CLIENTES`;
CREATE TABLE  `DB_TESTEWK`.`TB_CLIENTES` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `CIDADE` varchar(100) NOT NULL,
  `UF` char(2) NOT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (1,'JORGE','RIO DE JANEIRO','RJ');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (2,'PEDRO','GOIANIA','GO');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (3,'JONAS','SAO GONÇALO','RJ');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (4,'WEDER','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (5,'MARIA JOANA','SÃO PAULO','SP');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (6,'MARTA ALMEIDA','MACEIO','AL');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (7,'JULIA FERREIRA','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (8,'FATIMA','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (9,'RODRIGO','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (10,'JENNIFER','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (11,'CARMEM LUCIA','CUIABA','MT');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (12,'OLIVEIRA','BELO HORIZONTE','MG');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (13,'JOSE ALMEIDA','OURO BRANCO','MG');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (14,'CLIENTE 14','SALVADOR','BA');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (15,'CLIENTE 15','FEIRA DE SANTANA','BA');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (16,'CLIENTE 16','SALVADO','BA');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (17,'CLIENTE 17','NATAL','RN');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (18,'CLIENTE 18','MOSSORO','RN');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (19,'CLIENTE 19','PORTO ALEGRE','RS');
INSERT INTO `TB_CLIENTES` (`codigo`,`nome`,`cidade`,`uf`) VALUES (20,'CLIENTE 20','CANOAS','RS');

DROP TABLE IF EXISTS `DB_TESTEWK`.`TB_PRODUTOS`;
CREATE TABLE  `DB_TESTEWK`.`TB_PRODUTOS` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(150) NOT NULL,
  `PRECO_VENDA` decimal(11,3) NOT NULL DEFAULT 0.000,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (1,'PRODUTO 1','20.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (2,'PRODUTO 2','15.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (3,'PRODUTO 3','150.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (4,'PRODUTO 4','25.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (5,'PRODUTO 5','505.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (6,'PRODUTO 6','48.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (7,'PRODUTO 7','42.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (8,'PRODUTO 8','79.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (9,'PRODUTO 9','53.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (10,'PRODUTO 10','15.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (11,'PRODUTO 11','11.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (12,'PRODUTO 12','3.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (13,'PRODUTO 13','5.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (14,'PRODUTO 14','65.550');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (15,'PRODUTO 15','70.770');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (16,'PRODUTO 16','29.900');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (17,'PRODUTO 17','3.000');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (18,'PRODUTO 18','305.500');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (19,'PRODUTO 19','10.550');
INSERT INTO `TB_PRODUTOS` (`codigo`,`descricao`,`preco_venda`) VALUES (20,'PRODUTO 20','55.540');

DROP TABLE IF EXISTS `DB_TESTEWK`.`TB_PEDIDOS`;
CREATE TABLE  `DB_TESTEWK`.`TB_PEDIDOS` (
  `NUMEROPEDIDO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_EMISSAO` date NOT NULL,
  `CODIGO_CLIENTE` int(11) NOT NULL,
  `VALOR_TOTAL` decimal(11,3) NOT NULL,
  PRIMARY KEY (`NUMEROPEDIDO`),
  KEY `FK_TB_PEDIDOS_1` (`CODIGO_CLIENTE`),
  CONSTRAINT `FK_TB_PEDIDOS_1` FOREIGN KEY (`CODIGO_CLIENTE`) REFERENCES `TB_CLIENTES` (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DB_TESTEWK`.`TB_PEDIDOS_PRODUTOS`;
CREATE TABLE  `DB_TESTEWK`.`TB_PEDIDOS_PRODUTOS` (
  `CODIGO_PEDIDO_PRODUTO` int(11) NOT NULL AUTO_INCREMENT,
  `NUMEROPEDIDO` int(11) NOT NULL,
  `CODIGO_PRODUTO` int(11) NOT NULL,
  `QUANTIDADE` decimal(11,3) NOT NULL,
  `VALOR_UNITARIO` decimal(11,3) NOT NULL,
  `VALOR_TOTAL` decimal(11,3) NOT NULL DEFAULT 0.000,
  PRIMARY KEY (`CODIGO_PEDIDO_PRODUTO`),
  KEY `FK_TB_PEDIDOS_PROD_1` (`CODIGO_PRODUTO`),
  KEY `FK_TB_PEDIDOS_PROD_2` (`NUMEROPEDIDO`),
  CONSTRAINT `FK_TB_PEDIDOS_PROD_1` FOREIGN KEY (`CODIGO_PRODUTO`) REFERENCES `TB_PRODUTOS` (`CODIGO`),
  CONSTRAINT `FK_TB_PEDIDOS_PROD_2` FOREIGN KEY (`NUMEROPEDIDO`) REFERENCES `TB_PEDIDOS` (`NUMEROPEDIDO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

